// Autogenerated by the Generate Class from Layout plugin, version 0.2.0
// Layout file: UI/layouts/Menus/Dialogs/StartScenarioDialog.layout

class SCR_StartScenarioDialogWidgets
{
	static const ResourceName s_sLayout = "{D1AE71CF9CF46D25}UI/layouts/Menus/Dialogs/StartScenarioDialog.layout";
	ResourceName GetLayout() { return s_sLayout; }

	TextWidget m_ScenarioNameText;

	ImageWidget m_ScenarioImage;

	ButtonWidget m_JoinButton;
	SCR_NavigationButtonComponent m_JoinButtonComponent;

	ButtonWidget m_HostButton;
	SCR_NavigationButtonComponent m_HostButtonComponent;

	ButtonWidget m_PlayButton;
	SCR_NavigationButtonComponent m_PlayButtonComponent;

	bool Init(Widget root)
	{
		m_ScenarioNameText = TextWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.VerticalLayout0.m_ScenarioNameText"));

		m_ScenarioImage = ImageWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.VerticalLayout0.HorizontalLayout0.m_ScenarioImage"));

		m_JoinButton = ButtonWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.VerticalLayout0.HorizontalLayout0.PlayablePC.m_JoinButton"));
		m_JoinButtonComponent = SCR_NavigationButtonComponent.Cast(m_JoinButton.FindHandler(SCR_NavigationButtonComponent));

		m_HostButton = ButtonWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.VerticalLayout0.HorizontalLayout0.PlayablePC.m_HostButton"));
		m_HostButtonComponent = SCR_NavigationButtonComponent.Cast(m_HostButton.FindHandler(SCR_NavigationButtonComponent));

		m_PlayButton = ButtonWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.VerticalLayout0.HorizontalLayout0.PlayablePC.m_PlayButton"));
		m_PlayButtonComponent = SCR_NavigationButtonComponent.Cast(m_PlayButton.FindHandler(SCR_NavigationButtonComponent));

		return true;
	}
};
