// Autogenerated by the Generate Class from Layout plugin, version 0.2.0
// Layout file: UI/layouts/Menus/ContentBrowser/ScenariosMenu/ContentBrowser_ScenarioLine.layout

class SCR_ContentBrowser_ScenarioLineWidgets
{
	static const ResourceName s_sLayout = "{FEFDB7917AB8310F}UI/layouts/Menus/ContentBrowser/ScenariosMenu/ContentBrowser_ScenarioLine.layout";
	ResourceName GetLayout() { return s_sLayout; }

	SizeLayoutWidget m_FavouriteButtonOverlay;

	ButtonWidget m_FavouriteButton;
	SCR_ModularButtonComponent m_FavouriteButtonComponent;

	TextWidget m_NameText;

	TextWidget m_LastPlayedText;

	HorizontalLayoutWidget m_PlayerCount;

	ImageWidget m_SinglePlayerImage;

	SizeLayoutWidget m_PlayerCountSeparator;

	ImageWidget m_MultiPlayerImage;

	TextWidget m_PlayerCountText;

	HorizontalLayoutWidget m_Source;

	ImageWidget m_SourceImageOfficial;

	ImageWidget m_SourceImageCommunity;

	TextWidget m_SourceNameTextCommunity;

	TextWidget m_SourceNameTextOfficial;

	bool Init(Widget root)
	{
		m_FavouriteButtonOverlay = SizeLayoutWidget.Cast(root.FindWidget("LineHeight.Overlay0.LineContent.LineElements.m_FavouriteButtonOverlay"));

		m_FavouriteButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay0.LineContent.LineElements.m_FavouriteButtonOverlay.m_FavouriteButton"));
		m_FavouriteButtonComponent = SCR_ModularButtonComponent.Cast(m_FavouriteButton.FindHandler(SCR_ModularButtonComponent));

		m_NameText = TextWidget.Cast(root.FindWidget("LineHeight.Overlay0.LineContent.LineElements.NameSize.NameOverlay.m_NameText"));

		m_LastPlayedText = TextWidget.Cast(root.FindWidget("LineHeight.Overlay0.LineContent.LineElements.LastPlayedSize.LastPlayedOverlay.m_LastPlayedText"));

		m_PlayerCount = HorizontalLayoutWidget.Cast(root.FindWidget("LineHeight.Overlay0.LineContent.LineElements.PlayerCountSize.m_PlayerCount"));

		m_SinglePlayerImage = ImageWidget.Cast(root.FindWidget("LineHeight.Overlay0.LineContent.LineElements.PlayerCountSize.m_PlayerCount.m_SinglePlayerImage"));

		m_PlayerCountSeparator = SizeLayoutWidget.Cast(root.FindWidget("LineHeight.Overlay0.LineContent.LineElements.PlayerCountSize.m_PlayerCount.m_PlayerCountSeparator"));

		m_MultiPlayerImage = ImageWidget.Cast(root.FindWidget("LineHeight.Overlay0.LineContent.LineElements.PlayerCountSize.m_PlayerCount.m_MultiPlayerImage"));

		m_PlayerCountText = TextWidget.Cast(root.FindWidget("LineHeight.Overlay0.LineContent.LineElements.PlayerCountSize.m_PlayerCount.m_PlayerCountText"));

		m_Source = HorizontalLayoutWidget.Cast(root.FindWidget("LineHeight.Overlay0.LineContent.LineElements.SourceSize.m_Source"));

		m_SourceImageOfficial = ImageWidget.Cast(root.FindWidget("LineHeight.Overlay0.LineContent.LineElements.SourceSize.m_Source.SourceImagesSize.SourceImagesOverlay.m_SourceImageOfficial"));

		m_SourceImageCommunity = ImageWidget.Cast(root.FindWidget("LineHeight.Overlay0.LineContent.LineElements.SourceSize.m_Source.SourceImagesSize.SourceImagesOverlay.m_SourceImageCommunity"));

		m_SourceNameTextCommunity = TextWidget.Cast(root.FindWidget("LineHeight.Overlay0.LineContent.LineElements.SourceSize.m_Source.SourceNameTextOverlay.m_SourceNameTextCommunity"));

		m_SourceNameTextOfficial = TextWidget.Cast(root.FindWidget("LineHeight.Overlay0.LineContent.LineElements.SourceSize.m_Source.SourceNameTextOverlay.m_SourceNameTextOfficial"));

		return true;
	}
};
