// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Menus/ContentBrowser/AddonManager/AddonListTab/AddonTools/ListAddonsPresets.layout

class SCR_ListAddonsPresetsWidgets
{
	static const ResourceName s_sLayout = "{DD79194A2478216B}UI/layouts/Menus/ContentBrowser/AddonManager/AddonListTab/AddonTools/ListAddonsPresets.layout";
	ResourceName GetLayout() { return s_sLayout; }

	FrameWidget m_Root;
	SCR_AddonsPresetsSubMenu m_RootComponent;

	ScrollLayoutWidget m_ScrollPresets;
	SCR_ListBoxComponent m_ScrollPresetsComponent;

	bool Init(Widget root)
	{
		/*m_Root = FrameWidget.Cast(root.FindWidget("_error_"));
		m_RootComponent = SCR_AddonsPresetsSubMenu.Cast(m_Root.FindHandler(SCR_AddonsPresetsSubMenu));*/

		m_ScrollPresets = ScrollLayoutWidget.Cast(root.FindWidget("VerticalList.m_ScrollPresets"));
		m_ScrollPresetsComponent = SCR_ListBoxComponent.Cast(m_ScrollPresets.FindHandler(SCR_ListBoxComponent));

		return true;
	}
}
