// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Menus/ContentBrowser/AddonManager/AddonListTab/AddonLine.layout

class SCR_AddonLineWidgets
{
	static const ResourceName s_sLayout = "{1E9609F84FF1BF73}UI/layouts/Menus/ContentBrowser/AddonManager/AddonListTab/AddonLine.layout";
	ResourceName GetLayout() { return s_sLayout; }

	ImageWidget m_LineBackground;

	SizeLayoutWidget m_SizeMoveLeft;

	ButtonWidget m_MoveLeftButton;
	SCR_ModularButtonComponent m_MoveLeftButtonComponent;

	ButtonWidget m_ActionButton;
	SCR_ModularButtonComponent m_ActionButtonComponent;

	TextWidget m_NameText;

	HorizontalLayoutWidget m_HorizontalState;

	TextWidget m_StateText;

	ButtonWidget m_DeleteButton;
	SCR_ModularButtonComponent m_DeleteButtonComponent;

	ButtonWidget m_OpenDetailsButton;
	SCR_ModularButtonComponent m_OpenDetailsButtonComponent;

	ButtonWidget m_UpdateButton;
	SCR_ModularButtonComponent m_UpdateButtonComponent;

	ButtonWidget m_FixButton;
	SCR_ModularButtonComponent m_FixButtonComponent;

	SizeLayoutWidget m_SizeMoveRight;

	ButtonWidget m_MoveRightButton;
	SCR_ModularButtonComponent m_MoveRightButtonComponent;

	bool Init(Widget root)
	{
		m_LineBackground = ImageWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.m_LineBackground"));

		m_SizeMoveLeft = SizeLayoutWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_SizeMoveLeft"));

		m_MoveLeftButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_SizeMoveLeft.m_MoveLeftButton"));
		m_MoveLeftButtonComponent = SCR_ModularButtonComponent.Cast(m_MoveLeftButton.FindHandler(SCR_ModularButtonComponent));

		m_ActionButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_ActionButton"));
		m_ActionButtonComponent = SCR_ModularButtonComponent.Cast(m_ActionButton.FindHandler(SCR_ModularButtonComponent));

		m_NameText = TextWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.HorizontalLayout0.m_NameText"));

		m_HorizontalState = HorizontalLayoutWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.HorizontalLayout0.m_HorizontalState"));

		m_StateText = TextWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.HorizontalLayout0.m_HorizontalState.m_StateText"));

		m_DeleteButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_DeleteButton"));
		m_DeleteButtonComponent = SCR_ModularButtonComponent.Cast(m_DeleteButton.FindHandler(SCR_ModularButtonComponent));

		m_OpenDetailsButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_OpenDetailsButton"));
		m_OpenDetailsButtonComponent = SCR_ModularButtonComponent.Cast(m_OpenDetailsButton.FindHandler(SCR_ModularButtonComponent));

		m_UpdateButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_UpdateButton"));
		m_UpdateButtonComponent = SCR_ModularButtonComponent.Cast(m_UpdateButton.FindHandler(SCR_ModularButtonComponent));

		m_FixButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_FixButton"));
		m_FixButtonComponent = SCR_ModularButtonComponent.Cast(m_FixButton.FindHandler(SCR_ModularButtonComponent));

		m_SizeMoveRight = SizeLayoutWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_SizeMoveRight"));

		m_MoveRightButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_SizeMoveRight.m_MoveRightButton"));
		m_MoveRightButtonComponent = SCR_ModularButtonComponent.Cast(m_MoveRightButton.FindHandler(SCR_ModularButtonComponent));

		return true;
	}
}
