// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Menus/ContentBrowser/AddonManager/Dialogs/AddonsTools_PresetDialog.layout

class SCR_AddonsTools_PresetDialogWidgets
{
	static const ResourceName s_sLayout = "{A12D9824179B3214}UI/layouts/Menus/ContentBrowser/AddonManager/Dialogs/AddonsTools_PresetDialog.layout";
	ResourceName GetLayout() { return s_sLayout; }

	FrameWidget m_PresetListRoot;
	SCR_AddonsPresetsSubMenu m_PresetListRootComponent;

	ScrollLayoutWidget m_ScrollPresets;

	VerticalLayoutWidget m_PresetsList;

	bool Init(Widget root)
	{
		m_PresetListRoot = FrameWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.m_PresetListRoot"));
		m_PresetListRootComponent = SCR_AddonsPresetsSubMenu.Cast(m_PresetListRoot.FindHandler(SCR_AddonsPresetsSubMenu));

		m_ScrollPresets = ScrollLayoutWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.m_PresetListRoot.VerticalList.m_ScrollPresets"));

		m_PresetsList = VerticalLayoutWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.m_PresetListRoot.VerticalList.m_ScrollPresets.m_PresetsList"));

		return true;
	}
}
