// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Menus/Common/DetailsPanel/ContentDetailsPanelBase.layout

class SCR_ContentDetailsPanelBaseWidgets
{
	static const ResourceName s_sLayout = "{CB5B93884BFE5954}UI/layouts/Menus/Common/DetailsPanel/ContentDetailsPanelBase.layout";
	ResourceName GetLayout() { return s_sLayout; }

	SizeLayoutWidget m_TopSize;

	OverlayWidget m_BackendImage;

	ImageWidget m_Image;

	ButtonWidget m_LoadingOverlay;
	SCR_LoadingOverlay m_LoadingOverlayComponent;

	BlurWidget m_Blur;

	ImageWidget m_BackgroundImage;

	ImageWidget m_AnimationImage;
	SCR_SpinningWidgetComponent m_AnimationImageComponent;

	TextWidget m_Text;

	FrameWidget m_MainArea;

	TextWidget m_NameText;

	HorizontalLayoutWidget m_RatingOverlay;

	ImageWidget m_RatingIcon;

	TextWidget m_RatingText;

	TextWidget m_AuthorNameText;

	HorizontalLayoutWidget m_TypeOverlay;

	TextWidget m_TypeText;

	HorizontalLayoutWidget m_DownloadedOverlay;

	TextWidget m_DownloadedText;

	HorizontalLayoutWidget m_LastPlayedOverlay;

	TextWidget m_LastPlayedText;

	TextWidget m_DescriptionText;

	HorizontalLayoutWidget m_AddonStateOverlay;

	TextWidget m_AddonStateText;

	ImageWidget m_AddonStateIcon;

	HorizontalLayoutWidget m_AddonSizeOverlay;

	TextWidget m_AddonSizeText;

	TextWidget m_VersionText;

	bool Init(Widget root)
	{
		m_TopSize = SizeLayoutWidget.Cast(root.FindWidget("m_TopSize"));

		m_BackendImage = OverlayWidget.Cast(root.FindWidget("m_TopSize.m_BackendImage"));

		m_Image = ImageWidget.Cast(root.FindWidget("m_TopSize.m_BackendImage.ImageScale.m_Image"));

		m_LoadingOverlay = ButtonWidget.Cast(root.FindWidget("m_TopSize.m_BackendImage.m_LoadingOverlay"));
		m_LoadingOverlayComponent = SCR_LoadingOverlay.Cast(m_LoadingOverlay.FindHandler(SCR_LoadingOverlay));

		m_Blur = BlurWidget.Cast(root.FindWidget("m_TopSize.m_BackendImage.m_LoadingOverlay.loadingOverlayRoot1.m_Blur"));

		m_BackgroundImage = ImageWidget.Cast(root.FindWidget("m_TopSize.m_BackendImage.m_LoadingOverlay.loadingOverlayRoot1.m_BackgroundImage"));

		m_AnimationImage = ImageWidget.Cast(root.FindWidget("m_TopSize.m_BackendImage.m_LoadingOverlay.loadingOverlayRoot1.m_AnimationImage"));
		m_AnimationImageComponent = SCR_SpinningWidgetComponent.Cast(m_AnimationImage.FindHandler(SCR_SpinningWidgetComponent));

		m_Text = TextWidget.Cast(root.FindWidget("m_TopSize.m_BackendImage.m_LoadingOverlay.loadingOverlayRoot1.m_Text"));

		m_MainArea = FrameWidget.Cast(root.FindWidget("Bottom.m_MainArea"));

		m_NameText = TextWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.Line1.m_NameText"));

		m_RatingOverlay = HorizontalLayoutWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.Line1.m_RatingOverlay"));

		m_RatingIcon = ImageWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.Line1.m_RatingOverlay.Frame1.Frame0.m_RatingIcon"));

		m_RatingText = TextWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.Line1.m_RatingOverlay.m_RatingText"));

		m_AuthorNameText = TextWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.m_AuthorNameText"));

		m_TypeOverlay = HorizontalLayoutWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.Line0.m_TypeOverlay"));

		m_TypeText = TextWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.Line0.m_TypeOverlay.m_TypeText"));

		m_DownloadedOverlay = HorizontalLayoutWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.Line2.m_DownloadedOverlay"));

		m_DownloadedText = TextWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.Line2.m_DownloadedOverlay.m_DownloadedText"));

		m_LastPlayedOverlay = HorizontalLayoutWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.Line2.m_LastPlayedOverlay"));

		m_LastPlayedText = TextWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.Line2.m_LastPlayedOverlay.m_LastPlayedText"));

		m_DescriptionText = TextWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.m_DescriptionText"));

		m_AddonStateOverlay = HorizontalLayoutWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.StateAndSize.m_AddonStateOverlay"));

		m_AddonStateText = TextWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.StateAndSize.m_AddonStateOverlay.m_AddonStateText"));

		m_AddonStateIcon = ImageWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.StateAndSize.m_AddonStateOverlay.Scale0.m_AddonStateIcon"));

		m_AddonSizeOverlay = HorizontalLayoutWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.StateAndSize.m_AddonSizeOverlay"));

		m_AddonSizeText = TextWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.StateAndSize.m_AddonSizeOverlay.m_AddonSizeText"));

		m_VersionText = TextWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.VersionTextSize.m_VersionText"));

		return true;
	}
};
