//! used to grab the first id-matching Field Manual entry
enum EFieldManualEntryId
{
	NONE,

	EDITOR_INTRO,
	EDITOR_ACCESS,
	//EDITOR_MODES,
	EDITOR_PLAYER,
	EDITOR_CAMERA,
	EDITOR_CAMERA_PHOTO,
	EDITOR_MAP,
	EDITOR_TOOLBARS,
	EDITOR_SELECTING,
	EDITOR_CONTENT_BROWSER,
	EDITOR_PLACING,
	EDITOR_TRANSFORMING,
	EDITOR_SLOTS,
	EDITOR_COMMANDING_AI,
	EDITOR_COMMANDING_PLAYERS,
	EDITOR_ATTRIBUTES_GLOBAL,
	EDITOR_ATTRIBUTES_ENTITY,
	//EDITOR_TAKING_OVER_AI,
	EDITOR_LAYERS,
	
	CONFLICT_OVERVIEW,
	CONFLICT_BUILDING,
	CONFLICT_MHQ,
	CONFLICT_RANKS,
	CONFLICT_REINFORCEMENTS,
	CONFLICT_REQUESTING_VEHICLES,
	CONFLICT_RESPAWN,
	CONFLICT_SEIZING_BASES,
	CONFLICT_SERVICES,
	CONFLICT_SKILLS,
	CONFLICT_SUPPLIES
};
