#ifndef NO_AR_RESPAWN_TIMER_TIMESTAMP
#define AR_RESPAWN_TIMER_TIMESTAMP
#endif

#ifndef NO_AR_CAMPAIGN_TIMESTAMP
#define AR_CAMPAIGN_TIMESTAMP
#endif

#ifndef NO_AR_LOGIN_TIMESTAMP
#define AR_LOGIN_TIMESTAMP
#endif

#ifndef NO_AR_MINE_DETECTION_TIMESTAMP
#define AR_MINE_DETECTION_TIMESTAMP
#endif

#ifndef NO_AR_CATALOG_SPAWN_TIMESTAMP
#define AR_CATALOG_SPAWN_TIMESTAMP
#endif

#ifndef NO_AR_DEFENDER_SPAWN_TIMESTAMP
#define AR_DEFENDER_SPAWN_TIMESTAMP
#endif

#ifndef NO_AR_HINT_UI_TIMESTAMP
#define AR_HINT_UI_TIMESTAMP
#endif

#ifndef NO_AR_EDITOR_DISCONNECT_TIMESTAMP
#define AR_EDITOR_DISCONNECT_TIMESTAMP
#endif

#ifndef NO_AR_SESSION_DURATION_TIMESTAMP
#define AR_SESSION_DURATION_TIMESTAMP
#endif

#ifndef NO_AR_LOCAL_PLAYER_PENALTY_TIMESTAMP
#define AR_LOCAL_PLAYER_PENALTY_TIMESTAMP
#endif
