// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/HUD/WeaponInfo/WeaponInfo.layout

class SCR_WeaponInfoWidgets
{
	static const ResourceName s_sLayout = "{8170DE93810F928A}UI/layouts/HUD/WeaponInfo/WeaponInfo.layout";
	ResourceName GetLayout() { return s_sLayout; }

	VerticalLayoutWidget m_WeaponInfoPanel;

	HorizontalLayoutWidget m_Optics;

	RichTextWidget m_OpticsText;

	HorizontalLayoutWidget m_AmmoType;

	RichTextWidget m_AmmoTypeText;

	OverlayWidget m_AmmoType_Sniper;

	OverlayWidget m_AmmoType_Incendiary;

	OverlayWidget m_AmmoType_Smoke;

	OverlayWidget m_AmmoType_Frag;

	OverlayWidget m_AmmoType_HEAT;

	OverlayWidget m_AmmoType_HE;

	OverlayWidget m_AmmoType_AP;

	OverlayWidget m_AmmoType_FMJ;

	OverlayWidget m_AmmoType_Tracer;

	HorizontalLayoutWidget m_Zeroing;

	RichTextWidget m_ZeroingText;

	HorizontalLayoutWidget m_Main;

	OverlayWidget m_Firemode;

	ImageWidget m_FiremodeGlow;

	ImageWidget m_FiremodeIcon;

	OverlayWidget m_MagazineIndicator;

	ImageWidget m_MagazineGlow;

	ImageWidget m_MagazineBackground;

	ImageWidget m_MagazineOutline;

	ImageWidget m_MagazineProgress;

	SizeLayoutWidget m_MagCount;

	RichTextWidget m_MagCountText;

	bool Init(Widget root)
	{
		m_WeaponInfoPanel = VerticalLayoutWidget.Cast(root.FindAnyWidget("m_WeaponInfoPanel"));

		m_Optics = HorizontalLayoutWidget.Cast(root.FindAnyWidget("m_Optics"));

		m_OpticsText = RichTextWidget.Cast(root.FindAnyWidget("m_OpticsText"));

		m_AmmoType = HorizontalLayoutWidget.Cast(root.FindAnyWidget("m_AmmoType"));

		m_AmmoTypeText = RichTextWidget.Cast(root.FindAnyWidget("m_AmmoTypeText"));

		m_AmmoType_Sniper = OverlayWidget.Cast(root.FindAnyWidget("m_AmmoType_Sniper"));

		m_AmmoType_Incendiary = OverlayWidget.Cast(root.FindAnyWidget("m_AmmoType_Incendiary"));

		m_AmmoType_Smoke = OverlayWidget.Cast(root.FindAnyWidget("m_AmmoType_Smoke"));

		m_AmmoType_Frag = OverlayWidget.Cast(root.FindAnyWidget("m_AmmoType_Frag"));

		m_AmmoType_HEAT = OverlayWidget.Cast(root.FindAnyWidget("m_AmmoType_HEAT"));

		m_AmmoType_HE = OverlayWidget.Cast(root.FindAnyWidget("m_AmmoType_HE"));

		m_AmmoType_AP = OverlayWidget.Cast(root.FindAnyWidget("m_AmmoType_AP"));

		m_AmmoType_FMJ = OverlayWidget.Cast(root.FindAnyWidget("m_AmmoType_FMJ"));

		m_AmmoType_Tracer = OverlayWidget.Cast(root.FindAnyWidget("m_AmmoType_Tracer"));

		m_Zeroing = HorizontalLayoutWidget.Cast(root.FindAnyWidget("m_Zeroing"));

		m_ZeroingText = RichTextWidget.Cast(root.FindAnyWidget("m_ZeroingText"));

		m_Main = HorizontalLayoutWidget.Cast(root.FindAnyWidget("m_Main"));

		m_Firemode = OverlayWidget.Cast(root.FindAnyWidget("m_Firemode"));

		m_FiremodeGlow = ImageWidget.Cast(root.FindAnyWidget("m_FiremodeGlow"));

		m_FiremodeIcon = ImageWidget.Cast(root.FindAnyWidget("m_FiremodeIcon"));

		m_MagazineIndicator = OverlayWidget.Cast(root.FindAnyWidget("m_MagazineIndicator"));

		m_MagazineGlow = ImageWidget.Cast(root.FindAnyWidget("m_MagazineGlow"));

		m_MagazineBackground = ImageWidget.Cast(root.FindAnyWidget("m_MagazineBackground"));

		m_MagazineOutline = ImageWidget.Cast(root.FindAnyWidget("m_MagazineOutline"));

		m_MagazineProgress = ImageWidget.Cast(root.FindAnyWidget("m_MagazineProgress"));

		m_MagCount = SizeLayoutWidget.Cast(root.FindAnyWidget("m_MagCount"));

		m_MagCountText = RichTextWidget.Cast(root.FindAnyWidget("m_MagCountText"));

		return true;
	}
};
