// Autogenerated by the Generate Class from Layout plugin, version 0.2.0
// Layout file: UI/layouts/Menus/Common/FilterPanel/FilterPanel.layout

class SCR_FilterPanelWidgets
{
	static const ResourceName s_sLayout = "{B720EF58C3BBB377}UI/layouts/Menus/Common/FilterPanel/FilterPanel.layout";
	ResourceName GetLayout() { return s_sLayout; }

	ButtonWidget m_FilterButton;
	SCR_ModularButtonComponent m_FilterButtonComponent;

	ButtonWidget m_FilterSearch;
	SCR_EditBoxSearchComponent m_FilterSearchComponent;

	HorizontalLayoutWidget m_FilterButtonsLayout;

	TextWidget m_FilterButtonsCountText;

	OverlayWidget m_MainContent;

	OverlayWidget m_FilterListBoxOverlay;

	OverlayWidget m_FilterListBox;
	SCR_ListBoxComponent m_FilterListBoxComponent;

	bool Init(Widget root)
	{
		m_FilterButton = ButtonWidget.Cast(root.FindWidget("MenuPanel0.VerticalLayout0.TopBarHeight.TopBar.Content.ButtonsAndEditBox.m_FilterButton"));
		m_FilterButtonComponent = SCR_ModularButtonComponent.Cast(m_FilterButton.FindHandler(SCR_ModularButtonComponent));

		m_FilterSearch = ButtonWidget.Cast(root.FindWidget("MenuPanel0.VerticalLayout0.TopBarHeight.TopBar.Content.ButtonsAndEditBox.m_FilterSearch"));
		m_FilterSearchComponent = SCR_EditBoxSearchComponent.Cast(m_FilterSearch.FindHandler(SCR_EditBoxSearchComponent));

		m_FilterButtonsLayout = HorizontalLayoutWidget.Cast(root.FindWidget("MenuPanel0.VerticalLayout0.TopBarHeight.TopBar.Content.ButtonsAndEditBox.m_FilterButtonsLayout"));

		m_FilterButtonsCountText = TextWidget.Cast(root.FindWidget("MenuPanel0.VerticalLayout0.TopBarHeight.TopBar.Content.m_FilterButtonsCountText"));

		m_MainContent = OverlayWidget.Cast(root.FindWidget("MenuPanel0.VerticalLayout0.Content.m_MainContent"));

		m_FilterListBoxOverlay = OverlayWidget.Cast(root.FindWidget("MenuPanel0.VerticalLayout0.Content.m_FilterListBoxOverlay"));

		m_FilterListBox = OverlayWidget.Cast(root.FindWidget("MenuPanel0.VerticalLayout0.Content.m_FilterListBoxOverlay.m_FilterListBox"));
		m_FilterListBoxComponent = SCR_ListBoxComponent.Cast(m_FilterListBox.FindHandler(SCR_ListBoxComponent));

		return true;
	}
};
