// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Menus/ContentBrowser/Dialogs/DownloadConfirmationDialog.layout

class SCR_DownloadConfirmationDialogWidgets
{
	static const ResourceName s_sLayout = "{68802C0CD3C11CAA}UI/layouts/Menus/ContentBrowser/Dialogs/DownloadConfirmationDialog.layout";
	ResourceName GetLayout() { return s_sLayout; }

	VerticalLayoutWidget m_MainAddonSection;

	ButtonWidget m_MainAddonLine;
	SCR_DownloadManager_AddonDownloadLine m_MainAddonLineComponent;
	SCR_ModularButtonComponent m_MainAddonLineComponent1;

	VerticalLayoutWidget m_OtherAddonsSection;

	TextWidget m_OtherAddonsMessage;

	VerticalLayoutWidget m_OtherAddonsList;

	ImageWidget m_UpdateSpacer;

	TextWidget m_UpdateAddonsMessage;

	VerticalLayoutWidget m_UpdateAddonsList;

	HorizontalLayoutWidget m_SummarySection;

	SizeLayoutWidget m_AddonSizeOverlay;

	TextWidget m_TotalAddonSizeText;

	bool Init(Widget root)
	{
		m_MainAddonSection = VerticalLayoutWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.ContentSizeConstraints.ContentVerticalLayout.VerticalLayout.m_MainAddonSection"));

		m_MainAddonLine = ButtonWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.ContentSizeConstraints.ContentVerticalLayout.VerticalLayout.m_MainAddonSection.Overlay.m_MainAddonLine"));
		m_MainAddonLineComponent = SCR_DownloadManager_AddonDownloadLine.Cast(m_MainAddonLine.FindHandler(SCR_DownloadManager_AddonDownloadLine));
		m_MainAddonLineComponent1 = SCR_ModularButtonComponent.Cast(m_MainAddonLine.FindHandler(SCR_ModularButtonComponent));

		m_OtherAddonsSection = VerticalLayoutWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.ContentSizeConstraints.ContentVerticalLayout.VerticalLayout.m_OtherAddonsSection"));

		m_OtherAddonsMessage = TextWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.ContentSizeConstraints.ContentVerticalLayout.VerticalLayout.m_OtherAddonsSection.m_OtherAddonsMessage"));

		m_OtherAddonsList = VerticalLayoutWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.ContentSizeConstraints.ContentVerticalLayout.VerticalLayout.m_OtherAddonsSection.OtherAddonsScrollSize.Overlay.ScrollLayout.AddonListWrap.m_OtherAddonsList"));

		m_UpdateSpacer = ImageWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.ContentSizeConstraints.ContentVerticalLayout.VerticalLayout.m_OtherAddonsSection.OtherAddonsScrollSize.Overlay.ScrollLayout.AddonListWrap.m_UpdateSpacer"));

		m_UpdateAddonsMessage = TextWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.ContentSizeConstraints.ContentVerticalLayout.VerticalLayout.m_OtherAddonsSection.OtherAddonsScrollSize.Overlay.ScrollLayout.AddonListWrap.m_UpdateAddonsMessage"));

		m_UpdateAddonsList = VerticalLayoutWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.ContentSizeConstraints.ContentVerticalLayout.VerticalLayout.m_OtherAddonsSection.OtherAddonsScrollSize.Overlay.ScrollLayout.AddonListWrap.m_UpdateAddonsList"));

		m_SummarySection = HorizontalLayoutWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.ContentSizeConstraints.ContentVerticalLayout.VerticalLayout.m_SummarySection"));

		m_AddonSizeOverlay = SizeLayoutWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.ContentSizeConstraints.ContentVerticalLayout.VerticalLayout.m_SummarySection.m_AddonSizeOverlay"));

		m_TotalAddonSizeText = TextWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.ContentSizeConstraints.ContentVerticalLayout.VerticalLayout.m_SummarySection.m_AddonSizeOverlay.AddonSizeOverlay.m_TotalAddonSizeText"));

		return true;
	}
};
