// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Menus/ContentBrowser/DownloadManager/DownloadManager_CircleProgressIndicator.layout

class SCR_DownloadManager_CircleProgressIndicatorWidgets
{
	static const ResourceName s_sLayout = "{4B007F47AFF5C04D}UI/layouts/Menus/ContentBrowser/DownloadManager/DownloadManager_CircleProgressIndicator.layout";
	ResourceName GetLayout() { return s_sLayout; }

	ImageWidget m_ProgressCircle;

	ImageWidget m_DownloadDoneImage;

	TextWidget m_QueueSizeText;

	ButtonWidget m_DownloadButton;
	SCR_ModularButtonComponent m_DownloadButtonComponent;

	bool Init(Widget root)
	{
		m_ProgressCircle = ImageWidget.Cast(root.FindWidget("CircleSize.CircleImages.m_ProgressCircle"));

		m_DownloadDoneImage = ImageWidget.Cast(root.FindWidget("CircleSize.QueueSize.m_DownloadDoneImage"));

		m_QueueSizeText = TextWidget.Cast(root.FindWidget("CircleSize.QueueSize.m_QueueSizeText"));

		m_DownloadButton = ButtonWidget.Cast(root.FindWidget("m_DownloadButton"));
		m_DownloadButtonComponent = SCR_ModularButtonComponent.Cast(m_DownloadButton.FindHandler(SCR_ModularButtonComponent));

		return true;
	}
}
