const int SOUND_CHANNEL_COUNT = 6;

enum ESoundName
{
	// Conifer
	BIRD_CONIFER_CLOSE_JAY1 = 0,
	BIRD_CONIFER2_CLOSE_UNKNOWN8,
	BIRD_CONIFER_CLOSE_TOWHEE2,
	BIRD_CONIFER_CLOSE_TOWHEE3,
	BIRD_CONIFER_CLOSE_UNKNOWN1,
	BIRD_CONIFER2_CLOSE_GSWOODPACKER,
	BIRD_CONIFER2_CLOSE_UNKNOWN6,
	BIRD_CONIFER2_CLOSE_UNKNOWN9,
	BIRD_CONIFER2_CLOSE_UNKNOWN10,
	BIRD_CONIFER2_CLOSE_UNKNOWN11,
	BIRD_CONIFER2_CLOSE_UNKNOWN12,
	BIRD_CONIFER2_CLOSE_UNKNOWN13,
	BIRD_CONIFER2_CLOSE_UNKNOWN14,
	BIRD_CONIFER2_CLOSE_UNKNOWN15,
	BIRD_CONIFER_MID_CROW = 30,
	BIRD_CONIFER_MID_JAY2,
	BIRD_CONIFER_MID_RAVEN1,
	BIRD_CONIFER2_MID_TIT1,
	BIRD_CONIFER2_MID_UNKNOWN1,
	BIRD_CONIFER2_MID_UNKNOWN6,
	BIRD_CONIFER2_MID_UNKNOWN7,
	SQUIRREL_CONIFER_MID_1 = 50,
	SQUIRREL_CONIFER_MID_2,
	BIRD_CONIFER_DIST_RAVEN1 = 60,
	BIRD_CONIFER_DIST_RAVEN2,
	BIRD_CONIFER_DIST_THRUSH,
	BIRD_CONIFER_DIST_UNKNOWN1,
	BIRD_CONIFER2_DIST_TIT1,
	BIRD_CONIFER2_DIST_UNKNOWN5,
	BIRD_CONIFER2_DIST_UNKNOWN6,
	BIRD_CONIFER2_DIST_WOODPECKER,
	
	// Night Close 80
	// Night Mid 85
	BIRD_CONIFER_MID_OWL3 = 85,
	BIRD_CONIFER_MID_MAGPIE,
	BIRD_CONIFER_MID_OWLSHRIEK4,
	
	// Night Dist 90
	BIRD_CONIFER_DIST_OWL1 = 90,
	BIRD_CONIFER_DIST_OWL2,
	BIRD_CONIFER_DIST_SCOPSOWL1,
	BIRD_CONIFER_DIST_SCOPSOWL2,
	BIRD_CONIFER_DIST_OWLSHRIEK1,
	BIRD_CONIFER_DIST_OWLSHRIEK2,
	BIRD_CONIFER_DIST_OWLSHRIEK3,
	
	// Leafy
	BIRD_LEAFY_CLOSE_GROSBEAK = 100,
	BIRD_LEAFY_CLOSE_QUAIL,
	BIRD_LEAFY_CLOSE_SPARROW,
	BIRD_LEAFY_CLOSE_WARBLER1,
	BIRD_LEAFY_CLOSE_WARBLER2,
	BIRD_LEAFY_CLOSE_TIT1,
	BIRD_LEAFY_CLOSE_UNKNOWN1,
	BIRD_LEAFY_CLOSE_UNKNOWN8,
	BIRD_LEAFY_MID_UNKNOWN2 = 130,
	BIRD_LEAFY_MID_UNKNOWN5,
	BIRD_LEAFY_MID_UNKNOWN6,
	BIRD_LEAFY_MID_UNKNOWN7,
	BIRD_LEAFY_DIST_UNKNOWN3 = 160,
	BIRD_LEAFY_DIST_UNKNOWN4,
	BIRD_LEAFY_DIST_UNKNOWN7,
	BIRD_LEAFY_DIST_UNKNOWN8,
	
	// Night Close 180
	// Night Mid 185
	BIRD_LEAFY_MID_NIGHTINGALE1 = 185,
	BIRD_LEAFY_MID_NIGHTINGALE2,
	// Night Dist 190
	BIRD_LEAFY_MID_NIGHTINGALE3,
	BIRD_LEAFY_DIST_NIGHTINGALE4 = 190,
	BIRD_LEAFY_DIST_NIGHTINGALE5,
	
	
	// Leafy domestic
	// Insect
	INSECT_INSECT = 300,
	INSECT_GRASSHOPPER,
	INSECT_CICADAS,
	INSECT_CONIFER_HARSH1,
	INSECT_CONIFER_HARSH2,
	INSECT_CONIFER_CRICKET1,
	INSECT_CONIFER_CRICKET2,
	INSECT_CONIFER_HIGH1,
	INSECT_CONIFER_HIGH2,
	INSECT_CORNFIELD_UNKNOWN1,
	INSECT_MEADOW2_CRICKET1,
	INSECT_MEADOW2_DISTANT_CRICKET1,
	INSECT_MEADOW2_CICADAS1,
	INSECT_MEADOW_DISTANT_CRICKET1,
	INSECT_MEADOW_DISTANT_KATYDID1,
	INSECT_MEADOW_GRASSHOPPER2,
	INSECT_MEADOW_FLY,
	// Details
	DETAIL_CONIFER = 400,
	//DELETE
	DETAIL_TREECREAK,
	DETAIL_TREECREAKSMALL,
	DETAIL_FALLINGLEAVES = 430,
	DETAIL_TREECREAKDISTANT = 460,
	
	// --- OCEAN ---
	// Close 500
	// Mid 530
	BIRD_OCEAN_MID_SEAGULL1 = 530,
	// Dist 560
	BIRD_OCEAN_DIST_SEAGULL1 = 560,
	
	// Grass Short Insect 600
	// 600 PL Morning
	// 610 PL Noon
	INSECT_GRASSSHORT_NOON_CICADAS = 610,
	// 620 PL Evening
	INSECT_GRASSSHORT_EVENING_CICADAS = 620,
	// 630 PL Night
	INSECT_GRASSSHORT_NIGHT_CRICKET = 630,
	// 640 SL Morning
	// 650 SL Noon
	INSECT_GRASSSHORT_NOON_SL_CRICKET = 650,
	// 660 SL Evening
	INSECT_GRASSSHORT_EVENING_SL_CRICKET1 = 660,
	INSECT_GRASSSHORT_EVENING_SL_CRICKET2,
	INSECT_GRASSSHORT_EVENING_SL_KATYDID,
	// 670 SL Night
	INSECT_GRASSSHORT_NIGHT_SL_CRICKET = 670,
	INSECT_GRASSSHORT_NIGHT_SL_MARSHCRICKET,
	// 680 Misc
		
	// Grass Tall Insect 700
	//700
	
	//710
	INSECT_GRASSTTALL_NOON_GRASSHOPPER = 710,
	//720
	INSECT_GRASSTTALL_EVENING = 720,
	//730
	INSECT_GRASSTTALL_NIGHT_CRICKET = 730,
	INSECT_GRASSTTALL_NIGHT_KATYDID,
	//740 SL Morning
	
	//750 SL Noon
	INSECT_GRASSTTALL_NOON_SL_GRASSHOPPER = 750,
	INSECT_GRASSTTALL_NOON_SL_GRASSHOPPER_SHORT,
	//760 SL Evening
	INSECT_GRASSTTALL_EVENING_SL_GRASSHOPPER = 760,
	//770 SL Night
	INSECT_GRASSTTALL_NIGHT_SL_CRICKET = 770,
	//780 Misc
	INSECT_GRASSTTALL_GRASSHOPPER_WINGS = 780,
	INSECT_GRASSTTALL_FLY,
	
	// Conifer Insect 800
	// Morning SL 840
	INSECT_CONIFER_MORNING_SL_HARSH1 = 840,
	INSECT_CONIFER_MORNING_SL_HARSH2,
	// Noon SL 850
	INSECT_CONIFER_NOON_SL_HIGH1 = 850,
	INSECT_CONIFER_NOON_SL_HIGH2,
	// Evening SL 860
	INSECT_CONIFER_EVENING_SL_CRICKET = 860,
	INSECT_CONIFER_EVENING_SL_CRICKETLONG,
	// Night SL 870
	INSECT_CONIFER_NIGHT_SL_CRICKET = 870,
	INSECT_CONIFER_NIGHT_SL_FROG1,
	INSECT_CONIFER_NIGHT_SL_FROG2,
	// Misc 880
	INSECT_CONIFER_MOSQUITO = 880,
	
	// Leafy Insect 900
	// Morning SL 940
	INSECT_LEAFY_MORNING_SL_CRICKET = 940,
	// Noon SL 950
	INSECT_LEAFY_NOON_SL_CRICKET = 950,
	INSECT_LEAFY_NOON_SL_HEIGH,
	// Evening SL 960
	INSECT_LEAFY_EVENING_SL_CRICKET1 = 960,
	INSECT_LEAFY_EVENING_SL_CRICKET2,
	// Night SL 970
	INSECT_LEAFY_NIGHT_SL_CRICKET1 = 970,
	INSECT_LEAFY_NIGHT_SL_CRICKET2,
	INSECT_LEAFY_NIGHT_SL_CRICKET3,
	INSECT_LEAFY_NIGHT_SL_CRICKET4,
	
	// --- CROPFIELD --- 
	// Close 1000
	INSECT_CROPFIELD_DAY_CICADAS = 1000,
	// Mid 1030
	WIND_CROPFIELD = 1030,
	// Dist 1060
		
	// --- POND ---
	// Close 1100
	// Mid 1130
	FROG_POND_MID_EDIBLEFROG1 = 1130,
	FROG_POND_MID_EDIBLEFROG2,
	FROG_POND_MID_EDIBLEFROG3,
	FROG_POND_MID_EDIBLEFROG4,
	// Dist 1160
	BIRD_POND_DIST_DUCK = 1160,
	BIRD_POND_DIST_DUCKAGITATED,
	BIRD_POND_DIST_DUCKS,
	BIRD_POND_DIST_EURASIANCOOT,
	BIRD_POND_DIST_GHOOSE1,
	BIRD_POND_DIST_GHOOSE2,
	
	// --- CONCRETE ---
	// Close 1200
	// Mid 1230
	WIND_CONCRETE = 1230,
	// Dist 1260
};

enum ESoundEntityGroup
{
	TREE_CONIFER,
	TREE_LEAFY,
	TREE_DOMESTIC,
};

const int SOUND_TYPE_COUNT = 5;

enum ESoundType
{
	BIRD_ENTITY,
	BIRD_TERRAIN_MID,
	BIRD_TERRAIN_DIST,
	INSECT_MID,
	MISC_NOATT
};

enum ESoundEnvironmentType
{
	MEADOW,
	FOREST,
	HOUSES,
	SEA
};


enum ESoundSpawnDistance
{
	CLOSE,
	MID,
	DIST
};

const int SOUND_GROUP_COUNT = 7;

enum ESoundGroup
{
	//ENTITY_CONIFER,
	//ENTITY_LEAFY,
	//ENTITY_DOMESTIC,
	MEADOW_GRASS_SHORT,
	MEADOW_GRASS_TALL,
	FOREST_CONIFER,
	FOREST_LEAFY,
	CROPFIELD,
	CONCRETE,
	OCEAN,
	POND
};

[BaseContainerProps(configRoot: true)]
class SCR_AmbientSoundsEventsConfig
{
	[Attribute("", UIWidgets.Object, "Sound events definitions")]
	ref array<ref SCR_SoundType> m_aSoundType;
			
	[Attribute("", UIWidgets.Object, "Spawning behaviour definition")]
	ref array<ref SCR_SoundSpawnDefinitionGroup> m_aSoundSpawnDefinitionGroup;
	
	[Attribute("0 0 1 1", UIWidgets.GraphDialog, "",  params: "1 1 0 0")]
	ref Curve m_TimeModifier;
	
	[Attribute("0 0 1 1", UIWidgets.GraphDialog, "",  params: "1 1 0 0")]
	ref Curve m_WindModifier;
	
	[Attribute("0 0 1 1", UIWidgets.GraphDialog, "",  params: "1 1 0 0")]
	ref Curve m_RainModifier;
		
	[Attribute("", UIWidgets.Object, "Always changing signal definition")]
	ref array<ref SCR_AlwaysChangingSignal> m_aAlwaysChangingSignal;
};