// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Menus/ContentBrowser/Tile/ContentBrowserTile.layout

class SCR_ContentBrowserTileWidgets
{
	static const ResourceName s_sLayout = "{B7FFC0754752F6D3}UI/layouts/Menus/ContentBrowser/Tile/ContentBrowserTile.layout";
	ResourceName GetLayout() { return s_sLayout; }

	VerticalLayoutWidget m_NormalMode;

	SizeLayoutWidget m_MainAreaSizeRatio;

	OverlayWidget m_BackendImage;
	SCR_WorkshopItemBackendImageComponent m_BackendImageComponent;

	FrameWidget m_ShowOnMainButtonHover;

	TextWidget m_HintText;

	FrameWidget m_HideOnMainButtonHover;

	HorizontalLayoutWidget m_RatingOverlay;

	TextWidget m_RatingText;

	HorizontalLayoutWidget m_AddonSizeOverlay;

	HorizontalLayoutWidget m_BackendSource;

	ImageWidget m_BackendSourceIcon;

	TextWidget m_BackendSourceText;

	TextWidget m_AddonSizeText;

	ButtonWidget m_FavouriteButton;
	SCR_ModularButtonComponent m_FavouriteButtonComponent;

	ButtonWidget m_MainButton;
	SCR_ModularButtonComponent m_MainButtonComponent;

	TextWidget m_DependencyCountText;

	ButtonWidget m_DependencyHover;

	ButtonWidget m_DependentHover;

	FrameWidget m_NamesHorizontalAnimation;
	SCR_HorizontalScrollAnimationComponent m_NamesHorizontalAnimationComponent;

	TextWidget m_NameText;

	TextWidget m_AuthorNameText;

	ProgressBarWidget m_DownloadProgressBar;

	ButtonWidget m_EnableButton;
	SCR_ModularButtonComponent m_EnableButtonComponent;

	FrameWidget m_BlockedMode;

	PanelWidget m_BorderPanel;

	bool Init(Widget root)
	{
		m_NormalMode = VerticalLayoutWidget.Cast(root.FindWidget("overlay.m_NormalMode"));

		m_MainAreaSizeRatio = SizeLayoutWidget.Cast(root.FindWidget("overlay.m_NormalMode.m_MainAreaSizeRatio"));

		m_BackendImage = OverlayWidget.Cast(root.FindWidget("overlay.m_NormalMode.m_MainAreaSizeRatio.MainArea.m_BackendImage"));
		m_BackendImageComponent = SCR_WorkshopItemBackendImageComponent.Cast(m_BackendImage.FindHandler(SCR_WorkshopItemBackendImageComponent));

		m_ShowOnMainButtonHover = FrameWidget.Cast(root.FindWidget("overlay.m_NormalMode.m_MainAreaSizeRatio.MainArea.m_ShowOnMainButtonHover"));

		m_HintText = TextWidget.Cast(root.FindWidget("overlay.m_NormalMode.m_MainAreaSizeRatio.MainArea.m_ShowOnMainButtonHover.m_HintText"));

		m_HideOnMainButtonHover = FrameWidget.Cast(root.FindWidget("overlay.m_NormalMode.m_MainAreaSizeRatio.MainArea.m_HideOnMainButtonHover"));

		m_RatingOverlay = HorizontalLayoutWidget.Cast(root.FindWidget("overlay.m_NormalMode.m_MainAreaSizeRatio.MainArea.m_HideOnMainButtonHover.m_RatingOverlay"));

		m_RatingText = TextWidget.Cast(root.FindWidget("overlay.m_NormalMode.m_MainAreaSizeRatio.MainArea.m_HideOnMainButtonHover.m_RatingOverlay.m_RatingText"));

		m_AddonSizeOverlay = HorizontalLayoutWidget.Cast(root.FindWidget("overlay.m_NormalMode.m_MainAreaSizeRatio.MainArea.m_HideOnMainButtonHover.m_AddonSizeOverlay"));

		m_BackendSource = HorizontalLayoutWidget.Cast(root.FindWidget("overlay.m_NormalMode.m_MainAreaSizeRatio.MainArea.m_HideOnMainButtonHover.m_AddonSizeOverlay.m_BackendSource"));

		m_BackendSourceIcon = ImageWidget.Cast(root.FindWidget("overlay.m_NormalMode.m_MainAreaSizeRatio.MainArea.m_HideOnMainButtonHover.m_AddonSizeOverlay.m_BackendSource.Size.Overlay.m_BackendSourceIcon"));

		m_BackendSourceText = TextWidget.Cast(root.FindWidget("overlay.m_NormalMode.m_MainAreaSizeRatio.MainArea.m_HideOnMainButtonHover.m_AddonSizeOverlay.m_BackendSource.m_BackendSourceText"));

		m_AddonSizeText = TextWidget.Cast(root.FindWidget("overlay.m_NormalMode.m_MainAreaSizeRatio.MainArea.m_HideOnMainButtonHover.m_AddonSizeOverlay.m_AddonSizeText"));

		m_FavouriteButton = ButtonWidget.Cast(root.FindWidget("overlay.m_NormalMode.m_MainAreaSizeRatio.MainArea.Frame.m_FavouriteButton"));
		m_FavouriteButtonComponent = SCR_ModularButtonComponent.Cast(m_FavouriteButton.FindHandler(SCR_ModularButtonComponent));

		m_MainButton = ButtonWidget.Cast(root.FindWidget("overlay.m_NormalMode.m_MainAreaSizeRatio.MainArea.Frame.m_MainButton"));
		m_MainButtonComponent = SCR_ModularButtonComponent.Cast(m_MainButton.FindHandler(SCR_ModularButtonComponent));

		m_DependencyCountText = TextWidget.Cast(root.FindWidget("overlay.m_NormalMode.m_MainAreaSizeRatio.MainArea.Frame.m_DependencyCountText"));

		m_DependencyHover = ButtonWidget.Cast(root.FindWidget("overlay.m_NormalMode.m_MainAreaSizeRatio.MainArea.Frame.DependencyIndicators.m_DependencyHover"));

		m_DependentHover = ButtonWidget.Cast(root.FindWidget("overlay.m_NormalMode.m_MainAreaSizeRatio.MainArea.Frame.DependencyIndicators.m_DependentHover"));

		m_NamesHorizontalAnimation = FrameWidget.Cast(root.FindWidget("overlay.m_NormalMode.BottomBar.Frame.NamesFadeoutTextFrame.m_NamesHorizontalAnimation"));
		m_NamesHorizontalAnimationComponent = SCR_HorizontalScrollAnimationComponent.Cast(m_NamesHorizontalAnimation.FindHandler(SCR_HorizontalScrollAnimationComponent));

		m_NameText = TextWidget.Cast(root.FindWidget("overlay.m_NormalMode.BottomBar.Frame.NamesFadeoutTextFrame.m_NamesHorizontalAnimation.m_NameText"));

		m_AuthorNameText = TextWidget.Cast(root.FindWidget("overlay.m_NormalMode.BottomBar.Frame.NamesFadeoutTextFrame.m_NamesHorizontalAnimation.m_AuthorNameText"));

		m_DownloadProgressBar = ProgressBarWidget.Cast(root.FindWidget("overlay.m_NormalMode.BottomBar.Frame.m_DownloadProgressBar"));

		m_EnableButton = ButtonWidget.Cast(root.FindWidget("overlay.m_NormalMode.BottomBar.Frame.MainButtonOverlay.m_EnableButton"));
		m_EnableButtonComponent = SCR_ModularButtonComponent.Cast(m_EnableButton.FindHandler(SCR_ModularButtonComponent));

		m_BlockedMode = FrameWidget.Cast(root.FindWidget("overlay.m_BlockedMode"));

		m_BorderPanel = PanelWidget.Cast(root.FindWidget("overlay.m_BorderPanel"));

		return true;
	}
}
