// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Menus/ContentBrowser/DetailsMenu/ContentBrowserDetailsMenu.layout

class SCR_ContentBrowserDetailsMenuWidgets
{
	static const ResourceName s_sLayout = "{BF887B4F2E09DB82}UI/layouts/Menus/ContentBrowser/DetailsMenu/ContentBrowserDetailsMenu.layout";
	ResourceName GetLayout() { return s_sLayout; }

	ButtonWidget m_BackgroundButton;
	SCR_EventHandlerComponent m_BackgroundButtonComponent;

	TextWidget m_InstanceText;

	OverlayWidget m_Menu;

	ImageWidget m_ProgressCircle;

	ImageWidget m_DownloadDoneImage;

	TextWidget m_QueueSizeText;

	ButtonWidget m_Button;
	SCR_ModularButtonComponent m_ButtonComponent;

	bool Init(Widget root)
	{
		m_BackgroundButton = ButtonWidget.Cast(root.FindWidget("m_BackgroundButton"));
		m_BackgroundButtonComponent = SCR_EventHandlerComponent.Cast(m_BackgroundButton.FindHandler(SCR_EventHandlerComponent));

		m_InstanceText = TextWidget.Cast(root.FindWidget("m_InstanceText"));

		m_Menu = OverlayWidget.Cast(root.FindWidget("m_Menu"));

		m_ProgressCircle = ImageWidget.Cast(root.FindWidget("m_Menu.SizeBase.VerticalLayout0.Header.Overlay.DownloadManagerProgressIndicator0.CircleSize.CircleImages.m_ProgressCircle"));

		m_DownloadDoneImage = ImageWidget.Cast(root.FindWidget("m_Menu.SizeBase.VerticalLayout0.Header.Overlay.DownloadManagerProgressIndicator0.CircleSize.QueueSize.m_DownloadDoneImage"));

		m_QueueSizeText = TextWidget.Cast(root.FindWidget("m_Menu.SizeBase.VerticalLayout0.Header.Overlay.DownloadManagerProgressIndicator0.CircleSize.QueueSize.m_QueueSizeText"));

		m_Button = ButtonWidget.Cast(root.FindWidget("m_Menu.SizeBase.VerticalLayout0.Header.Overlay.DownloadManagerProgressIndicator0.m_Button"));
		m_ButtonComponent = SCR_ModularButtonComponent.Cast(m_Button.FindHandler(SCR_ModularButtonComponent));

		return true;
	}
};
