// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Menus/ServerBrowser/ServerHosting/ServerHostingTabs/ServerHostingMods.layout

class SCR_ServerHostingModsWidgets
{
	static const ResourceName s_sLayout = "{DE4EA9E0DA35261F}UI/layouts/Menus/ServerBrowser/ServerHosting/ServerHostingTabs/ServerHostingMods.layout";
	ResourceName GetLayout() { return s_sLayout; }

	SizeLayoutWidget m_DisabledAddonsPanel;

	ButtonWidget m_ButtonEnableAll;
	SCR_ModularButtonComponent m_ButtonEnableAllComponent;

	VerticalLayoutWidget m_DisabledAddonsList;

	SizeLayoutWidget m_EnabledAddonsPanel;

	ButtonWidget m_ButtonDisableAll;
	SCR_ModularButtonComponent m_ButtonDisableAllComponent;

	VerticalLayoutWidget m_EnabledAddonsList;

	bool Init(Widget root)
	{
		m_DisabledAddonsPanel = SizeLayoutWidget.Cast(root.FindWidget("HorizontalLayout0.m_DisabledAddonsPanel"));

		m_ButtonEnableAll = ButtonWidget.Cast(root.FindWidget("HorizontalLayout0.m_DisabledAddonsPanel.Overlay0.VerticalLayout0.TopBarHeight.TopBar.Content.HorizontalLayout0.m_ButtonEnableAll"));
		m_ButtonEnableAllComponent = SCR_ModularButtonComponent.Cast(m_ButtonEnableAll.FindHandler(SCR_ModularButtonComponent));

		m_DisabledAddonsList = VerticalLayoutWidget.Cast(root.FindWidget("HorizontalLayout0.m_DisabledAddonsPanel.Overlay0.VerticalLayout0.Content.Scroll.m_DisabledAddonsList"));

		m_EnabledAddonsPanel = SizeLayoutWidget.Cast(root.FindWidget("HorizontalLayout0.m_EnabledAddonsPanel"));

		m_ButtonDisableAll = ButtonWidget.Cast(root.FindWidget("HorizontalLayout0.m_EnabledAddonsPanel.Overlay0.VerticalLayout0.TopBarHeight.TopBar.Content.HorizontalLayout0.m_ButtonDisableAll"));
		m_ButtonDisableAllComponent = SCR_ModularButtonComponent.Cast(m_ButtonDisableAll.FindHandler(SCR_ModularButtonComponent));

		m_EnabledAddonsList = VerticalLayoutWidget.Cast(root.FindWidget("HorizontalLayout0.m_EnabledAddonsPanel.Overlay0.VerticalLayout0.Content.Scroll.m_EnabledAddonsList"));

		return true;
	}
}
