//------------------------------------------------------------------------------------------------
//! This enum contains all IDs for DiagMenu entries added in script.
enum SCR_DebugMenuID
{
	// Camera
	DEBUGUI_DRAW_CAMERA_COLLISION_SOLVER = 0,
	
	// Character
	DEBUGUI_CHARACTER_MENU,
	DEBUGUI_CHARACTER_NOBANKING,
	DEBUGUI_CHARACTER_MUZZLE_CROSSHAIR,
	DEBUGUI_CHARACTER_DEBUG_VIEW,
	DEBUGUI_CHARACTER_ADS_CAMERA,
	//DEBUGUI_CHARACTER_WEAPON_MECHANICS,
	//DEBUGUI_CHARACTER_HEAD_HACK,
	DEBUGUI_CHARACTER_SCREEN_EFFECTS,
	DEBUGUI_CHARACTER_POSTPROCESSING_EFFECTS,
	DEBUGUI_CHARACTER_TRANSFORMATION,
	DEBUGUI_CHARACTER_HITREACTION_AIMMODIFIER,
	DEBUGUI_CHARACTER_RECOIL_CAMERASHAKE_DISABLE,
	DEBUGUI_CHARACTER_ADDITIONAL_CAMERASHAKE_DISABLE,
	DEBUGUI_CHARACTER_CAMERASHAKE_TEST_WINDOW,
	
	// Interactions
	DEBUGUI_INTERACTION_MENU,
	DEBUGUI_INTERACTION_HANDLER,
	DEBUGUI_INTERACTION_ADVANCED,
	DEBUGUI_INTERACTION_ENTITY,
	DEBUGUI_INTERACTION_NEARBY_CONTEXTS,
	DEBUGUI_INTERACTION_CONTEXT_DISTANCE,
	DEBUGUI_INTERACTION_CONTEXT_GIZMO_SCALE,
	DEBUGUI_INTERACTION_CONTEXT_DISTANCE_SCALE,
	DEBUGUI_INTERACTION_ALL_INSTANT,
	
	// Radial menu
	DEBUGUI_RADIALMENU_MENU,
	DEBUGUI_RADIALMENU_DIAGNOSTICS,
	DEBUGUI_RADIALMENU_LOGGING,
	
	// Inventory
	DEBUGUI_INVENTORY,
	
	// Nametags
	DEBUGUI_NAMETAGS,
	
	// Net
	DEBUGUI_GAME_MODE,
	DEBUGUI_RESPAWN_SYSTEM_INFO,
	//DEBUGUI_FACTION_SCORING,
	DEBUGUI_SCORING_SYSTEM,
	DEBUGUI_RESPAWN_TIMER_COMPONENT,
	
	// Survival
	DEBUGUI_SURVIVAL_MENU,
	DEBUGUI_SURVIVAL_SHOW_DEBUG_HUD,
	
	// Sounds
	DEBUGUI_SOUNDS_GLOBAL_SIGNALS,
	DEBUGUI_SOUNDS_AMBIENT_SIGNALS,
	DEBUGUI_SOUNDS_MPDESTRUCTION_SHOW_IMPULSEVALUES,
	DEBUGUI_SOUNDS_PRINT_MELEESURFACE,
	
	// Input manager
	DEBUGUI_INPUT_MANAGER,
	
	// Editor
	DEBUGUI_EDITOR,
	DEBUGUI_EDITOR_SHOW_DEBUG,
	DEBUGUI_EDITOR_IS_OPENED,
	DEBUGUI_EDITOR_CAN_OPEN,
	DEBUGUI_EDITOR_CAN_CLOSE,
	DEBUGUI_EDITOR_FORCE_LIMITED,
	DEBUGUI_EDITOR_LOG_GLOBAL_ATTRIBUTES,
	DEBUGUI_EDITOR_MODE,
	DEBUGUI_EDITOR_ASYNC_LOAD_DEBUG,
	DEBUGUI_EDITOR_NETWORK_DELAY,
	
	DEBUGUI_EDITOR_ENTITIES,
	DEBUGUI_EDITOR_ENTITIES_LOG_ALL,
	DEBUGUI_EDITOR_ENTITIES_LOG_TYPE,
	DEBUGUI_EDITOR_ENTITIES_LOG_AVAILABLE,
	DEBUGUI_EDITOR_ENTITIES_LOG_ACCESS_KEYS,
	DEBUGUI_EDITOR_ENTITIES_ACCESS_KEY,
	DEBUGUI_EDITOR_ENTITIES_ACCESS_KEY_TOGGLE,
	DEBUGUI_EDITOR_ENTITIES_ACCESS_KEY_ADMIN,
	DEBUGUI_EDITOR_ENTITIES_SELECT_LOG,
	DEBUGUI_EDITOR_ENTITIES_SELECT_ALL,
	DEBUGUI_EDITOR_ENTITIES_SELECT_NONE,
	DEBUGUI_EDITOR_ENTITIES_TEST_ENTITY_ACCESS_KEY,
	DEBUGUI_EDITOR_ENTITIES_TEST_ENTITY_ACCESS_KEY_TOGGLE,
	DEBUGUI_EDITOR_ENTITIES_TEST_ENTITY_LAYER,
	DEBUGUI_EDITOR_ENTITIES_TEST_ENTITY_SELECT,
	DEBUGUI_EDITOR_ENTITIES_TEST_ENTITY_FOCUS,
	DEBUGUI_EDITOR_ENTITIES_TEST_ENTITY_SHOW,
	DEBUGUI_EDITOR_ENTITIES_BUDGET_CAP,
	DEBUGUI_EDITOR_ENTITIES_LOG_BUDGET_CHANGES,
	DEBUGUI_EDITOR_ENTITIES_ENABLE_AI_PILOT_PLACE,
	DEBUGUI_EDITOR_SPECIFIC_LOG,
	DEBUGUI_EDITOR_ENTITIES_DISABLE,
	
	DEBUGUI_EDITOR_ACTIONS_MENU,
	DEBUGUI_EDITOR_ACTIONS_MENU_ICONS,
	DEBUGUI_EDITOR_ACTIONS_MENU_SHOWDISABLED,
	DEBUGUI_EDITOR_ACTIONS_MENU_WAYPOINTS_INPUT,
	
	DEBUGUI_EDITOR_TRANSFORM,
	DEBUGUI_EDITOR_TRANSFORM_START,
	DEBUGUI_EDITOR_TRANSFORM_CONFIRM,
	DEBUGUI_EDITOR_TRANSFORM_CANCEL,
	DEBUGUI_EDITOR_TRANSFORM_VERTICAL_MODE,
	DEBUGUI_EDITOR_TRANSFORM_VERTICAL_SNAP,
	
	DEBUGUI_SAVELOAD,
	DEBUGUI_SAVELOAD_SAVE,
	DEBUGUI_SAVELOAD_LOAD,
	DEBUGUI_SAVELOAD_LOG,
	
	DEBUGUI_EDITOR_GUI,
	DEBUGUI_EDITOR_GUI_TOOLBAR_FILL,
	
	// Manual Camera
	DEBUGUI_MANUAL_CAMERA,
	DEBUGUI_MANUAL_CAMERA_DEBUG,
	DEBUGUI_MANUAL_CAMERA_UNLIMITED,
	DEBUGUI_MANUAL_CAMERA_SPEED_BOOST_UP,
	DEBUGUI_MANUAL_CAMERA_FREE,
	DEBUGUI_MANUAL_CAMERA_CONTROL_PLAYER,
	DEBUGUI_MANUAL_CAMERA_VIEW_LINK,
	
	// Scripted AI debug
	DEBUGUI_AI_SCRIPT,
	DEBUGUI_AI_PRINT_DEBUG,
	DEBUGUI_AI_PRINT_GROUP_INFO,
	DEBUGUI_AI_PRINT_ACTIVITY,
	DEBUGUI_AI_PRINT_SHOT_STATISTICS,
	DEBUGUI_AI_DEBUG_CATEGORY,
	DEBUGUI_AI_SHOW_DEBUG_SHAPES,
	DEBUGUI_AI_SHOW_FRIENDLY_IN_AIM,
	DEBUGUI_AI_SHOW_TARGET_LASTSEEN,
	DEBUGUI_AI_CONFIGURE_STATISTICSDEBUG,
	DEBUGUI_AI_SELECT_FIXED_AGENT,
	DEBUGUI_AI_DEBUG_COVERS,
	DEBUGUI_AI_SEND_MESSAGE,
	DEBUGUI_AI_OPEN_DEBUG_PANEL,
	
	// Campaign
	DEBUGUI_CAMPAIGN_MENU,
	DEBUGUI_CAMPAIGN_SHOW_RELAYS,
	DEBUGUI_CAMPAIGN_INSTANT_CAPTURE,
	DEBUGUI_CAMPAIGN_EXECUTE_GAMEMODE,
	DEBUGUI_CAMPAIGN_EXECUTE_BASES,
	//DEBUGUI_CAMPAIGN_DETECT_RELAYS,
	DEBUGUI_CAMPAIGN_CAPTURE_RELAYS,
	DEBUGUI_CAMPAIGN_RANK_UP,
	DEBUGUI_CAMPAIGN_RANK_DOWN,
	DEBUGUI_CAMPAIGN_BASES_DIAG,
	
	// Tasks
	DEBUGUI_TASKS_MENU,
	DEBUGUI_EXECUTE_TASKS,
	DEBUGUI_SHOW_ALL_TASKS,
	
	// General
	DEBUGUI_COPY_ENF_VIEW_LINK,	
	DEBUGUI_BOUNDS_OVERLAP_PREFAB_DIAG,
	DEBUGUI_CURSOR_TARGET_PREFAB_DIAG,
	
	// Aim modifier
	DEBUGUI_AIMMODIFIER_MENU,
	
	DEBUGUI_AIMMODIFIER_LIN_X,
	DEBUGUI_AIMMODIFIER_LIN_Y,
	DEBUGUI_AIMMODIFIER_LIN_Z,
	DEBUGUI_AIMMODIFIER_ANG_X,
	DEBUGUI_AIMMODIFIER_ANG_Y,
	DEBUGUI_AIMMODIFIER_ANG_Z,
	DEBUGUI_AIMMODIFIER_TURN_X,
	DEBUGUI_AIMMODIFIER_TURN_Y,
	
	DEBUGUI_AIMMODIFIER_RESET,
	
	// UI
	DEBUGUI_UI_CLOSE_ALL_MENUS,
	DEBUGUI_UI_OPEN_MAIN_MENU,
	DEBUGUI_UI_LOG_UNDER_CURSOR,
	DEBUGUI_UI_SHOW_ALL_SETTINGS,
	DEBUGUI_UI_MAP_DEBUG_OPTIONS,
	
	//Particles
	DEBUGUI_PARTICLES_VEHICLE_DUST,
	
	// Weapons
	DEBUGUI_WEAPONS_MELEE_MENU,
	DEBUGUI_WEAPONS_MELEE_SHOW_EDITOR,
	DEBUGUI_WEAPONS_MELEE_ENABLE_GAME,
	DEBUGUI_WEAPONS_MELEE_SHOW_GAME,	
	DEBUGUI_WEAPONS_PIP_SIGHTS,
	
	DEBUGUI_HINT_IGNORE_SHOWN,
	
	//Tutorial
	DEBUGUI_TUTORIAL_MENU,
	DEBUGUI_TUTORIAL_STAGE,
};