// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/HUD/VON/VoNOverlay_Element.layout

class SCR_VoNOverlay_ElementWidgets
{
	static const ResourceName s_sLayout = "{25221F619214A722}UI/layouts/HUD/VON/VoNOverlay_Element.layout";
	ResourceName GetLayout() { return s_sLayout; }

	OverlayWidget m_wMicFrame;

	ImageWidget m_wMicBackground;

	ImageWidget m_wMic;

	ImageWidget m_wIconBackground;

	ImageWidget m_wIcon;

	OverlayWidget m_wDirectionFrame;

	ImageWidget m_wDirectionBackground;

	ImageWidget m_wDirection;

	TextWidget m_wFrequency;

	TextWidget m_wSeparator;

	TextWidget m_wName;

	OverlayWidget m_wChannelFrame;

	ImageWidget m_wChannelBackground;

	RichTextWidget m_wChannelText;

	bool Init(Widget root)
	{
		m_wMicFrame = OverlayWidget.Cast(root.FindAnyWidget("m_wMicFrame"));

		m_wMicBackground = ImageWidget.Cast(root.FindAnyWidget("m_wMicBackground"));

		m_wMic = ImageWidget.Cast(root.FindAnyWidget("m_wMic"));

		m_wIconBackground = ImageWidget.Cast(root.FindAnyWidget("m_wIconBackground"));

		m_wIcon = ImageWidget.Cast(root.FindAnyWidget("m_wIcon"));

		m_wDirectionFrame = OverlayWidget.Cast(root.FindAnyWidget("m_wDirectionFrame"));

		m_wDirectionBackground = ImageWidget.Cast(root.FindAnyWidget("m_wDirectionBackground"));

		m_wDirection = ImageWidget.Cast(root.FindAnyWidget("m_wDirection"));

		m_wFrequency = TextWidget.Cast(root.FindAnyWidget("m_wFrequency"));

		m_wSeparator = TextWidget.Cast(root.FindAnyWidget("m_wSeparator"));

		m_wName = TextWidget.Cast(root.FindAnyWidget("m_wName"));

		m_wChannelFrame = OverlayWidget.Cast(root.FindAnyWidget("m_wChannelFrame"));

		m_wChannelBackground = ImageWidget.Cast(root.FindAnyWidget("m_wChannelBackground"));

		m_wChannelText = RichTextWidget.Cast(root.FindAnyWidget("m_wChannelText"));

		return true;
	}
}
