// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Menus/ContentBrowser/AddonManager/AddonBar/AddonBar.layout

class SCR_WorkshopAddonBarWidgets
{
	static const ResourceName s_sLayout = "{E51B373A4E72E920}UI/layouts/Menus/ContentBrowser/AddonManager/AddonBar/AddonBar.layout";
	ResourceName GetLayout() { return s_sLayout; }

	ImageWidget m_ProgressCircle;

	ImageWidget m_DownloadDoneImage;

	TextWidget m_QueueSizeText;

	ButtonWidget m_DownloadButton;
	SCR_ModularButtonComponent m_DownloadButtonComponent;

	ButtonWidget m_UpdateButton;
	SCR_ButtonImageComponent m_UpdateButtonComponent;

	TextWidget m_OutdatedAddonsCountText;

	ButtonWidget m_PresetsButton;
	SCR_ButtonImageComponent m_PresetsButtonComponent;

	FrameWidget m_ModsCountFrame;

	TextWidget m_ModsCountText;

	SizeLayoutWidget m_SizePresetName;

	TextWidget m_TxtPresetName;

	HorizontalLayoutWidget m_AddonIconsLayout;

	bool Init(Widget root)
	{
		m_ProgressCircle = ImageWidget.Cast(root.FindAnyWidget("m_ProgressCircle"));

		m_DownloadDoneImage = ImageWidget.Cast(root.FindAnyWidget("m_DownloadDoneImage"));

		m_QueueSizeText = TextWidget.Cast(root.FindAnyWidget("m_QueueSizeText"));

		m_DownloadButton = ButtonWidget.Cast(root.FindAnyWidget("m_DownloadButton"));
		m_DownloadButtonComponent = SCR_ModularButtonComponent.Cast(m_DownloadButton.FindHandler(SCR_ModularButtonComponent));

		m_UpdateButton = ButtonWidget.Cast(root.FindAnyWidget("m_UpdateButton"));
		m_UpdateButtonComponent = SCR_ButtonImageComponent.Cast(m_UpdateButton.FindHandler(SCR_ButtonImageComponent));

		m_OutdatedAddonsCountText = TextWidget.Cast(root.FindAnyWidget("m_OutdatedAddonsCountText"));

		m_PresetsButton = ButtonWidget.Cast(root.FindAnyWidget("m_PresetsButton"));
		m_PresetsButtonComponent = SCR_ButtonImageComponent.Cast(m_PresetsButton.FindHandler(SCR_ButtonImageComponent));

		m_ModsCountFrame = FrameWidget.Cast(root.FindAnyWidget("m_ModsCountFrame"));

		m_ModsCountText = TextWidget.Cast(root.FindAnyWidget("m_ModsCountText"));

		m_SizePresetName = SizeLayoutWidget.Cast(root.FindAnyWidget("m_SizePresetName"));

		m_TxtPresetName = TextWidget.Cast(root.FindAnyWidget("m_TxtPresetName"));

		m_AddonIconsLayout = HorizontalLayoutWidget.Cast(root.FindAnyWidget("m_AddonIconsLayout"));

		return true;
	}
}
